### ISSUE TITLE
Aqara smart plug is not detected as plug/switch/light

### ISSUE THREAD

**Issue by mat1990dj** [treban/pimatic-raspbee#21]
I bought a new aqara smart plug (not the wall interated plug but the smart plug) and I have it on my deconz rest api but the raspbee plugin does only detect the plugin as a sensor (without proposing any type) and does not detect the switch

**Comment by sweebee** [comment]
I created a pull request for this #20. @treban can you merge this request?

**Comment by treban** [comment]
version 0.0.8 should fix this problem. PR #20 is merged.

**Comment by mat1990dj** [comment]
Still not fixed
When I add the device via auto discovery there's no proposed device and using switch does not work
![image](https://user-images.githubusercontent.com/5220059/47447390-a7defe00-d7bd-11e8-9d34-ed1f23f80023.png)

This is the debug info:
'15': 
   { etag: '47168cf06790ee8dc1044eea57ef9447',
     hascolor: false,
     manufacturername: 'LUMI',
     modelid: 'lumi.plug',
     name: 'Light 15',
     state: { alert: 'none', on: false, reachable: true },
     swversion: null,
     type: 'Smart plug',
     uniqueid: '00:15:8d:00:02:48:26:a8-01' }

**Comment by treban** [comment]
@mat1990dj please check version v0.0.10

**Comment by mat1990dj** [comment]
It works!
